name: run scraping.py

on:
  push:
    branches: 
      - main
#   schedule: 
#     - cron: '60 * * * *'

jobs: 
  run_schedule:
    runs-on: ubuntu-latest
    steps: 

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar python
        uses: actions/setup-python@v4

      - name: instalar os pacotes do requiremsnts
        run: python -m pip install pip install -r requirements.txt

      - name: executar arquivo de scrapping
        run: python scraping.py